name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 */7 * *"

jobs:
  check:
    name: Build and test
    if: github.repository == 'apache/pekko-grpc-quickstart-scala.g8'
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 11

      - name: Install sbt
        uses: sbt/setup-sbt@6c68d2fe8dfbc0a0534d70101baa2e0420e1a506 # v1.1.9

      - name: Cache Coursier cache
        uses: coursier/cache-action@4e2615869d13561d626ed48655e1a39e5b192b3c # 6.4.7

      - name: sbt & Paradox
        run: sbt test docs/paradox

      - name: Maven
        run: |-
          sbt new file://$PWD --name=hello-world-grpc --force && pushd hello-world-grpc &&  mvn test

      - name: Gradle
        run: |-
          sbt new file://$PWD --name=hello-world-grpc --force && pushd hello-world-grpc &&  ./gradlew --console=plain build -i --no-daemon
